// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpahgggrmsvavtpbjkll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwYWhnZ2dybXN2YXZ0cGJqa2xsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NzQyOTMsImV4cCI6MjA2MjQ1MDI5M30.JcTtHQ2hLZG_MpZAHlF0bYpL9Ner-m18okjP-C1N18w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);